### ISSUE TITLE
1.2.0 released? 

### ISSUE THREAD

**Issue by ErisDS** [dylang/node-rss#53]
Hi there, npm is reporting a version 1.2.0 published yesterday: `1.2.0': '2015-10-14T01:52:13.044Z`, however the package.json file still says 1.1.1 in master & there is no tag in the repo, so it's not possible for services like [david-dm](https://david-dm.org/tryghost/ghost) to tell us what has changed.

Is this missing or is 1.2.0 a mistake?

**Comment by dylang** [comment]
Yikes, you're right, it looks like I forgot to push changes to Github. Thanks for noticing!
