### ISSUE TITLE
Documented example for 'categories' doesn't validate according to W3C

### ISSUE THREAD

**Issue by mikemaccana** [dylang/node-rss#57]
Per README.md

> categories optional array of strings One or more categories this feed belongs to.

I'm using:

     categories: ['Technology', 'Information Security', 'Software Development'],

Which returns the following at the [W3C validator](https://validator.w3.org/feed/check.cgi):

    XML parsing error: <unknown>:1:1192: unbound prefix
    ategory><![CDATA[Software Development]]></category>

**Comment by ErisDS** [comment]
Hi @mikemaccana :) 

We're using pretty much the exact same thing in the Ghost source [see here](https://github.com/TryGhost/Ghost/blob/master/core/server/data/xml/rss/index.js#L146), and aren't seeing any errors with validation. 

Do you have an extended example, RSS snippet, or URL I could take a look at?

**Comment by mikemaccana** [comment]
Sample URL: https://certsimple.com/blog/rss.xml

Suspect the cause of the error is namespace prefix 'webfeeds' is totally missing. I.e.:

   xmlns:webfeeds="http://webfeeds.org/rss/1.0"

should exist on the <rss> element on the generated output but isn't.

**Comment by mikemaccana** [comment]
OK so I just needed:

    custom_namespaces: {
    	webfeeds: "http://webfeeds.org/rss/1.0"
    }

**Comment by mikemaccana** [comment]
To give some context, looks like the W3C validator was failing on:

     <webfeeds:logo>http://certsimple.com/images/blog/logo.svg</webfeeds:logo>

Not on the categories tag - the validator was a few characters off.

**Comment by mikemaccana** [comment]
PS. Thanks!
